### ISSUE TITLE
remove test dependencies from setup.py

### ISSUE THREAD

**Issue by knaaptime** [pysal/submodule_template#14]
lines 37 and [38](https://github.com/pysal/submodule_template/blob/6ea7d163302c40e908aeac8db5802bf5d6395fe4/setup.py#L38) define testing dependencies outside of `requirements_tests.txt` which will cause failures when releasing on conda-forge. 

Also, is `nose` the canonical test suite? I thought many of the pysal packages had migrated to pytest, but could be wrong

**Comment by knaaptime** [comment]
see, e.g. https://github.com/conda-forge/staged-recipes/pull/8350

**Comment by jGaboardi** [comment]
Addressed in #28
