### ISSUE TITLE
automated docs publishing

### ISSUE THREAD

**Issue by knaaptime** [pysal/submodule_template#33]
not sure the best place to put this, but the final automation step, imo, is to have the docs built automatically from source. That should be doable with [this action](https://github.com/marketplace/actions/deploy-to-github-pages-python) so ill carve out some time to try it out

**Comment by knaaptime** [comment]
the work here has been done for a couple years. Lets resolve this by adding an example yaml like https://github.com/pysal/spopt/blob/main/.github/workflows/build_docs.yml

**Comment by knaaptime** [comment]
xref https://github.com/pysal/giddy/issues/179

**Comment by martinfleis** [comment]
Shall we also try to figure out how to keep the version chooser? Having old releases, main and latest is quite useful.

**Comment by knaaptime** [comment]
+1

I'd also be interested in exploring an overhaul with [myst](https://myst-parser.readthedocs.io/en/latest/), but need a compelling motivation

**Comment by martinfleis** [comment]
We use across some projects and any new one is myst default. It is so much better over rst and can run along is, so you can have some files as rst and other as md. So the gradual transformation is easy.
