### ISSUE TITLE
Add pre-commit for formatting & linting

### ISSUE THREAD

**Issue by jGaboardi** [pysal/submodule_template#36]
We could add in a `.pre-commit-config.yml` and `setup.cfg` for automated code formatting and linting. Also, add `black`, `isort`, `flake8`, and ~~`pyflakes`~~ to requirements, etc.

See an example of all pieces in [`mapclassify`](https://github.com/pysal/mapclassify)
* [`.pre-commit-config.yaml`](https://github.com/pysal/mapclassify/blob/main/.pre-commit-config.yaml)
* [`setup.cfg`](https://github.com/pysal/mapclassify/blob/main/setup.cfg)
* [linting action](https://github.com/pysal/mapclassify/blob/0f9c71b546c20f68384acc896f1311de44740044/.github/workflows/testing.yml#L14-L19) performed prior to running tests

**Comment by knaaptime** [comment]
+1

**Comment by martinfleis** [comment]
What `pyflakes` do?

**Comment by jGaboardi** [comment]
I had thought that `flake8` *and* `pyflakes` were needed for linting. Though maybe I'm mistaken?

**Comment by martinfleis** [comment]
Only `flake8` as far as I know.

> If you like Pyflakes but also want stylistic checks, you want [flake8](https://pypi.org/project/flake8/), which combines Pyflakes with style checks against [PEP 8](https://www.python.org/dev/peps/pep-0008/) and adds per-project configuration ability.

(https://pypi.org/project/pyflakes/)

**Comment by jGaboardi** [comment]
Well, then. I stand corrected.
