### ISSUE TITLE
remove dual building?

### ISSUE THREAD

**Issue by ljwolf** [pysal/submodule_template#6]
Since `libpysal` is python 3-only, should we remove the [2to3 conversion in the setup.py](https://github.com/pysal/submodule_template/blob/master/setup.py#L4)?

**Comment by ljwolf** [comment]
ack I mean dual building, the dual testing should definitely be kept, and thank you for adding it @weikang9009!!

**Comment by weikang9009** [comment]
2to3 conversion (in the setup.py) is removed in https://github.com/pysal/submodule_template/pull/5

**Comment by weikang9009** [comment]
Solved by PR #5
